"""Idempotent deployment-only MediaMTX configuration generator."""
import ipaddress
import os
import re
import secrets
from settings import read_env


def prepare_live(root):
    env = root / 'config' / '.env'
    text = env.read_text('utf-8')
    values = read_env(text)
    config = root / 'config' / 'mediamtx.yml'
    marker = '# Generated by Relay live_setup.py; edit generator for advanced changes.\n'
    if config.exists() and not config.read_text('utf-8').startswith(marker):
        raise ValueError('config/mediamtx.yml 已存在且不是本工具生成，未覆盖；请备份并移走后重试')
    updates = {}
    for key, default in (('LIVE_INTERNAL_TOKEN', secrets.token_urlsafe(48)), ('LIVE_RTMP_PORT', '1935'), ('LIVE_RTSP_PORT', '8554')):
        if not values.get(key):
            updates[key] = default
    values.update(updates)
    if not re.fullmatch(r'[A-Za-z0-9_-]{32,128}', values['LIVE_INTERNAL_TOKEN']):
        raise ValueError('LIVE_INTERNAL_TOKEN 必须是 32–128 位随机字母、数字、下划线或短横线')
    for key in ('LIVE_RTMP_PORT', 'LIVE_RTSP_PORT'):
        if not values[key].isdigit() or not 1024 <= int(values[key]) <= 65535:
            raise ValueError(key + ' 必须在 1024–65535 之间')
    if values['LIVE_RTMP_PORT'] == values['LIVE_RTSP_PORT']:
        raise ValueError('直播推流和播放端口不能相同')
    host = values.get('LIVE_PUBLIC_HOST', '')
    if host:
        try:
            ipaddress.ip_address(host)
        except ValueError:
            if not re.fullmatch(r'[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?', host):
                raise ValueError('LIVE_PUBLIC_HOST 请填写裸域名或 IP，不含协议、路径和端口')
    if updates:
        text += '\n# Generated live transport settings; keep the token private.\n'
        text += ''.join(k + '=' + v + '\n' for k, v in updates.items())
        temporary = env.with_suffix('.live-part')
        temporary.write_text(text, encoding='utf-8')
        os.chmod(temporary, 0o600)
        if hasattr(os, 'chown'):
            original = env.stat()
            os.chown(temporary, original.st_uid, original.st_gid)
        temporary.replace(env)
    content = marker + '''logLevel: error
authMethod: http
authHTTPAddress: http://relay:8080/internal/live/TOKEN
authHTTPExclude: []
api: true
apiAddress: :9997
metrics: false
pprof: false
playback: false
rtsp: true
rtspTransports: [tcp]
rtspAddress: :8554
rtmp: true
rtmpAddress: :1935
hls: false
webrtc: false
srt: false
moq: false
pathDefaults:
  source: publisher
  record: false
  overridePublisher: false
paths:
  "~^live/[A-Za-z0-9_-]{32}$": {}
'''.replace('TOKEN', values['LIVE_INTERNAL_TOKEN'])
    temporary = config.with_suffix('.part')
    temporary.write_text(content, encoding='utf-8')
    os.chmod(temporary, 0o600)
    temporary.replace(config)


def compose_args(args, root):
    if args[:2] != ['docker', 'compose'] or args[2:] == ['version']:
        return args
    result = args[:2] + ['--env-file', 'config/.env', '-f', 'compose.yaml']
    for name in ('compose.override.yaml', 'compose.override.yml'):
        if (root / name).exists():
            result += ['-f', name]
            break
    return result + ['-f', 'compose.live.yaml'] + args[2:]
