/* Unified settings: uses the main page's api, auth, feedback and lifecycle. */
(() => {
let current=null,dirty=false,loading=null;
function render(result){dirty=false;$('settings-dirty').textContent='';current=result;$('fields').replaceChildren();const groups=new Map();for(const [key,meta] of Object.entries(result.schema)){let section=groups.get(meta.group);if(!section){section=document.createElement('section');const title=document.createElement('h2');title.textContent=meta.group;section.append(title);groups.set(meta.group,section);$('fields').append(section)}const label=document.createElement('label');label.htmlFor=key;label.textContent=meta.label;let input;const options=Array.isArray(meta.constraint)&&typeof meta.default==='string'||key==='DEFAULT_HEIGHT';if(options){input=document.createElement('select');for(const v of meta.constraint){const names={h264:'H.264',hevc:'HEVC（H.265）',none:'软件编码',nvenc:'NVIDIA NVENC',qsv:'Intel QSV',vaapi:'AMD / Intel VA-API（Linux）',amf:'AMD AMF（Windows）'};input.add(new Option(names[v]||v,v))}}else if(key==='FOOTER_NOTICE'){input=document.createElement('textarea');input.rows=4}else{input=document.createElement('input');input.type=typeof meta.default==='boolean'?'checkbox':typeof meta.default==='number'?'number':key==='NAS_API_KEY'?'password':'text';if(input.type==='number'){input.min=meta.constraint[0];input.max=meta.constraint[1];input.step=key.startsWith('BANDWIDTH_')?'any':'1'}if(input.type==='checkbox'){input.style.width='18px';input.checked=result.values[key]}if(input.type==='password'){input.autocomplete='new-password';input.placeholder=result.nas_key_configured?'已保存；留空保留':'尚未设置'}}input.id=key;if(input.type!=='checkbox')input.value=key==='NAS_API_KEY'?'':key==='CACHE_MAX_BYTES'?result.values[key]/1e9:result.values[key];if(key==='CACHE_MAX_BYTES'){input.min=meta.constraint[0]/1e9;input.max=meta.constraint[1]/1e9;input.step='any'}section.append(label,input);if(key==='CACHE_MAX_BYTES'){const tip=document.createElement('small');tip.textContent='默认 9 GB，仅统计媒体缓存。调低后淘汰旧缓存；正在读取或预载的缓存超过新上限时拒绝保存。Docker 镜像、日志及 NAS 临时文件另计。';section.append(tip)}}const notice=document.createElement('span');notice.textContent=result.values.FOOTER_NOTICE;notice.style.whiteSpace='pre-line';const link=document.createElement('a');link.textContent=result.values.FOOTER_ICP;link.href='https://beian.miit.gov.cn/';link.target='_blank';link.rel='noopener noreferrer';document.querySelector('.site-notice').replaceChildren(notice,document.createElement('br'),link);$('management').hidden=false}
async function load(){if(dirty&&!confirm('重新加载会丢弃未保存的修改，是否继续？'))return false;render(await api('/api/settings'));return true}
$('reload').onclick=()=>action(()=>withBusy($('reload'),'加载中…',async()=>{if(await load())$('message').textContent='已重新加载保存的设置。'}));
$('settings-form').addEventListener('input',()=>{dirty=true;$('settings-dirty').textContent='有未保存的修改，请点击保存到 .env。'});
$('settings-form').onsubmit=e=>{e.preventDefault();action(async()=>{if(!current)return;const values={};for(const [key,meta] of Object.entries(current.schema)){const input=$(key);values[key]=typeof meta.default==='boolean'?input.checked:typeof meta.default==='number'?(key==='CACHE_MAX_BYTES'?Math.round(Number(input.value)*1e9):Number(input.value)):input.value} $('save').disabled=true;$('save').textContent='正在保存…';try{render(await api('/api/settings','POST',{revision:current.revision,values}));$('message').textContent='已保存到 .env；全局设置已生效。NAS 硬件配置需单独应用。'}finally{$('save').disabled=false;$('save').textContent='保存到 .env'}})};
$('nas-read').onclick=()=>action(async()=>{$('nas-read').disabled=true;$('nas-read').textContent='正在读取…';try{const values=await api('/api/nas-config');for(const [key,value] of Object.entries(values)){if($(key).type==='checkbox')$(key).checked=value;else $(key).value=value}$('nas-result').textContent='已读取 NAS 配置并填入表单，尚未保存。'}finally{$('nas-read').disabled=false;$('nas-read').textContent='读取 NAS 当前配置到表单'}});
$('nas-apply').onclick=()=>action(async()=>{if(dirty)throw Error('有未保存的修改，请先保存到 .env，再应用到 Jellyfin。');$('nas-apply').disabled=true;$('nas-apply').textContent='正在应用并验证…';try{await api('/api/nas-config','POST',{revision:current.revision});$('nas-result').textContent='已应用到 Jellyfin，并回读验证配置一致。请测试实际硬件转码。'}finally{$('nas-apply').disabled=false;$('nas-apply').textContent='将已保存配置应用到 Jellyfin'}});

window.unifiedSettings={
 reset(){window.unifiedLive?.reset();current=null;dirty=false;loading=null;$('fields').replaceChildren();$('settings-dirty').textContent='';$('nas-result').textContent='';$('settings-view').hidden=true;$('dashboard-view').hidden=false;document.body.classList.remove('settings-active')},
 async route(){
  if(!connected)return;
  const open=location.hash==='#settings'||location.hash.startsWith('#setting-group-');
  const live=location.hash==='#live';window.unifiedLive?.enter(live);
  $('dashboard-view').hidden=open||live;$('settings-view').hidden=!open;document.body.classList.toggle('settings-active',open);
  document.querySelectorAll('.app-nav a').forEach(a=>a.classList.toggle('active',open?a.hash==='#settings':a.hash===location.hash||!location.hash&&a.hash==='#stats'));
  if(!open&&['#stats','#create-section','#library-heading'].includes(location.hash))requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView({block:'start'}));
  if(open&&!current){if(!loading){$('settings-loading').hidden=false;loading=action(load).finally(()=>{$('settings-loading').hidden=true;loading=null})}await loading}
 }
};
window.addEventListener('hashchange',()=>window.unifiedSettings.route());
if(location.pathname==='/settings')history.replaceState(null,'','/#settings');
window.unifiedSettings.route();
})();
